### ISSUE TITLE
Bug report If we received damage we have error message in the console (for more information I use PaperSpigot)

### ISSUE THREAD

**Issue by AK477-Dev** [mehboss/CustomRecipes#15]
### What happened?

I try your plugin but i constate if I received damage i have this message (for more information I use PaperSpigot)

### What was supposed to happen?

it's not supposed to happen

### How do I reproduce this issue?

```bash
If you use paperspigot and if any people attack you with sword (or other tool) he send error in the console
```

### Relevant log output

```shell
[18:17:03 ERROR]: Could not pass event EntityDamageByEntityEvent to CustomRecipes v1.8.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-TacoSpigot-fd3209f3]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-TacoSpigot-fd3209f3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-TacoSpigot-fd3209f3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-TacoSpigot-fd3209f3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-TacoSpigot-fd3209f3]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [server.jar:git-TacoSpigot-fd3209f3]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [server.jar:git-TacoSpigot-fd3209f3]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [server.jar:git-TacoSpigot-fd3209f3]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1118) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:860) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:754) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:801) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:504) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1086) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1387) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-TacoSpigot-fd3209f3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [server.jar:git-TacoSpigot-fd3209f3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [server.jar:git-TacoSpigot-fd3209f3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/entity/Trident
        at me.mehboss.recipe.EffectsManager.oneffect(EffectsManager.java:47) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor215.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-TacoSpigot-fd3209f3]
        ... 27 more
```

### Server Version

1.8

### Plugin Version

1.8

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello!
Thank you for reporting. I will push a fix here in the next hour or so!

**Comment by mehboss** [comment]
Hello,

Thank you again for reporting this issue. [Please refer here for resolution.](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=508247) Downloading this new update will resolve this issue.
