### ISSUE TITLE
[Question]: I have an issue where i cant add custom items because i dnot have an config in the recepie

### ISSUE THREAD

**Issue by Snic0509** [mehboss/CustomRecipes#26]
### What is your question?

I copie an existing recepie and when i reload the file stands in the console Could not find configuration section Veredlung in the recipe file: Veredlung.yml - (CaSeSeNsItIvE) - Skipping this recipe 

### Server Version

1.20

### Plugin Version

1.8.7

### Question Confirmation

- [X] I have checked the WIKI and the main page of the spigot resource, but still cannot find my answer.
- [X] I have provided sufficient information regarding my question.

**Comment by Valorless** [comment]
Greetings!
Could you provide me with a copy of the recipe? ^^

**Comment by Snic0509** [comment]
shoure 

CursedSword:
  Enabled: true
  Shapeless: true
  Item: DIAMOND_SWORD
  Item-Damage: none
  Amount: 1
  Placeable: true
  Ignore-Data: false
  Ignore-Model-Data: false
  Custom-Tagged: true
  Identifier: CURSED_SWORD
  Permission: crecipe.recipe.cursedsword
  Name: '&eCursed Sword'
  Lore:
  - '&fThe Cursed Sword'
  Effects:
  - POISON:20:2
  Hide-Enchants: true
  Enchantments:
  - DURABILITY:300
  ItemCrafting:
  - DDD
  - XPX
  - XPX
  Ingredients:
    D:
      Material: DIAMOND
      Identifier: none
      Amount: 1
      Name: Diamond Shrine
    P:
      Material: OAK_PLANKS
      Identifier: none
      Amount: 1
      Name: Wooden Board
  Item-Flags: []
  Attribute: []
  Custom-Model-Data: none
  Disabled-Worlds: []

**Comment by Valorless** [comment]
Thank you ^^

The issue should be that the recipe does not match the file.
The first line of the recipe which currently says `CursedSword:`, must match the name of the file. (without .yml)

I can see that you've ticked that you checked the wiki, but it appears you've missed [this section](https://github.com/mehboss/CustomRecipes/wiki/Common-Issues). :) 

I hope this helps fix the issue.

**Comment by Snic0509** [comment]
ok now i tried that an i cant reload the plugin i get this error in the consol 
[21:16:33 INFO]: Sonic_0509 issued server command: /customr reload
[21:16:33 WARN]: [CustomRecipes] Could not find configuration section Veredlung in the recipe file: Veredlung.yml - (CaSeSeNsItIvE) - Skipping this recipe
[21:16:33 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'customr' in plugin CustomRecipes v1.8.7
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-137]
at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-137]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2347) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2307) ~[?:?]
at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-137]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-137]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-137]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-137]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-137]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-137]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-137]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-137]
at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalStateException: Duplicate recipe ignored with ID customrecipes:cursed_sword
at net.minecraft.world.item.crafting.RecipeManager.addRecipe(RecipeManager.java:93) ~[?:?]
at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftShapelessRecipe.addToCraftingManager(CraftShapelessRecipe.java:47) ~[paper-1.20.1.jar:git-Paper-137]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.addRecipe(CraftServer.java:1541) ~[paper-1.20.1.jar:git-Paper-137]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.addRecipe(CraftServer.java:1507) ~[paper-1.20.1.jar:git-Paper-137]
at me.mehboss.recipe.RecipeManager.addItems(RecipeManager.java:440) ~[CustomRecipes(v1.8.7).jar:?]
at me.mehboss.recipe.Main.reload(Main.java:419) ~[CustomRecipes(v1.8.7).jar:?]
at me.mehboss.recipe.GiveRecipe.onCommand(GiveRecipe.java:107) ~[CustomRecipes(v1.8.7).jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

**Comment by Snic0509** [comment]
Nevermind my mistake i dint change the Identifier

**Comment by Valorless** [comment]
> Nevermind my mistake i dint change the Identifier

Awesome ^^
I'll tell Boss about the error right away, and have him look into the issue when he has time :)

**Comment by Snic0509** [comment]
I have another question about an another File whitch i trie to load up but it dident work 
i get this error : [CustomRecipes] Could not find configuration section Veredlung in the recipe file: Veredlung.yml - (CaSeSeNsItIvE) - Skipping this recipe 

and this is the file:
Veredelung:
  Enabled: true # Whether or not this recipe is enabled
  Shapeless: false # Whether or not you want it to have specific order in crafting
  Item: netherite_upgrade_smithing_template # Item ID
  Item-Damage: none # Used for when you need a specific type of item with a "19/00" or "13:4". leave to none if non exists.
  Amount: 1 # When you craft this item, this is the amount you will get from it.
  Placeable: true # If it is a block, you can choose to make it unplaceable.
  Ignore-Data: false # Whether or not metadata should be considered as a requirement for crafting
  Ignore-Model-Data: false # Whether or not you want model data to be considered even if ignore-data is set to true
  Custom-Tagged: true # Whether or not you want this item to be tagged with a custom item tag.
  Durability: '100' # 1-100. Remove section if not needed.
  Identifier: Cursed # Give your new recipe an identifier :).
  Permission: crecipe.recipe.veredelung # Give a player this permission to allow them to craft this item. Remove section if no permission wanted.
  Name: '&4&lVeredelung' # Name of the item, you can use color codes. Remove if not needed
  Lore:
  - '&c&lVerdelt Diamantene Werkzeuge und rüstungen'
  
  Hide-Enchants: true # Show enchants on item?
  Enchantments:
  - DURABILITY:300
  ItemCrafting:
  - EEE
  - XIX
  - XIX
  Ingredients:
    # DO NOT INCLUDE VARIABLE X AS AN INGREDIENT. THIS IS DEFAULTED TO AIR **
    E: # E is the letter I picked for emerald
      # REMOVE NAME SECTION OR SET TO 'none' IF NOT WANTED
      Material: DIAMOND # Material ENUM
      Identifier: none # Set to custom recipe 'identifier' to use a custom item as an ingredient
      Amount: 1 # Amount required in one slot to craft
    I:
      Material: IRON_INGOT
      Identifier: none
      Amount: 1
  Item-Flags: []
  # Add items flags to your item such as hide attributes
  Attribute: []
  # Adds a given amount of a specified attribute to the custom item.
  # Format: ATTRIBUTE:AMOUNT:SLOT
  Custom-Model-Data: none
  Disabled-Worlds: []
# Custom model data for texture packs. Only on MC 1.14+!

**Comment by Valorless** [comment]
It appears you've spelt the name incorrectly in the file ^^
The file is called `Veredlung`, but inside the file you've written `Veredelung`.

**Comment by Snic0509** [comment]
oh..... i see im stupid xD 
Thank you very mutch

**Comment by Valorless** [comment]
No worries, everyone makes mistakes.
I'm happy I could help. :)

If any other issues occur, please feel free to open another Issue; or re-open this if the issue is the same.
