### ISSUE TITLE
Recipes aren't working

### ISSUE THREAD

**Issue by mad4me** [mehboss/CustomRecipes#47]
### What happened?

I just installed CoustmRecipies to my test server and its giving me an warning message in the console and the recipes aren't working. All seems configured correctly (I didn't even changed the configuration file)

### What was supposed to happen?

To just install the plugin and work out of the box.

### How do I reproduce this issue?

```bash
I just installed the plugin and it doesn't work
```

### Relevant log output

```shell
[22:23:30 INFO]: [CustomRecipes] Made by MehBoss on Spigot. For support please PM me and I will get back to you as soon as possible!
[22:23:30 INFO]: [CustomRecipes] Loading Recipes..
[22:23:30 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.level.block.entity.TileEntity.m()
[22:23:30 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[22:23:30 WARN]:        at CustomRecipes(v1.8.8).jar//me.mehboss.recipe.NBTEditor.<clinit>(NBTEditor.java:248)
[22:23:30 WARN]:        at CustomRecipes(v1.8.8).jar//me.mehboss.recipe.RecipeManager.handleIdentifier(RecipeManager.java:66)
[22:23:30 WARN]:        at CustomRecipes(v1.8.8).jar//me.mehboss.recipe.RecipeManager.addItems(RecipeManager.java:331)
[22:23:30 WARN]:        at CustomRecipes(v1.8.8).jar//me.mehboss.recipe.Main.onEnable(Main.java:355)
[22:23:30 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[22:23:30 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[22:23:30 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[22:23:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[22:23:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639)
[22:23:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550)
[22:23:30 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[22:23:30 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[22:23:30 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
[22:23:30 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[22:23:30 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[22:23:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:23:31 INFO]: [CustomRecipes] Loaded 2 recipes.
```

### Relevant file configuration

```shell
All default configurations.
```

### Server Version

1.20.4

### Plugin Version

1.8.8

### Server Mode

Offline Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello mad4me,
I forgot to update an NBTEditor class to work with 1.20, which is the cause of the error and issue. I will do some testing now and notify you when I release it to Spigot. 

Thank you
