### ISSUE TITLE
1.21/PaperMC: Turning off all the recipes on server launch.

### ISSUE THREAD

**Issue by Nikoroq** [mehboss/CustomRecipes#52]
### What happened?

Every vanilla recipe being turned off as soon as every server plugin has been loaded. Any item can't be crafted, plugin commands isn't working, as well plugins seems to be disabled (even though vanilla recipes are gone). Server reports this:

![1 (2)](https://github.com/mehboss/CustomRecipes/assets/135438574/aa520aa9-6147-4a55-ab6a-caa2c273779e)

![2](https://github.com/mehboss/CustomRecipes/assets/135438574/e64f82c9-c34c-41f9-9e1c-b7b6404ddc82)

### What was supposed to happen?

Plugin start. Plugin work. Consumer happy.

### How do I reproduce this issue?

```bash
1. Use PaperMC core on 1.21 version
2. Install plugin in the plugins folder
3. Start server
4. ???
5. All your recipes are belongs to us.
```

### Relevant log output

```shell
[08:25:20] [Server thread/ERROR]: Error occurred while enabling CustomRecipes v1.9 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at CustomRecipes(v1.9).jar/me.mehboss.recipe.RecipeManager.handleIdentifier(RecipeManager.java:70) ~[CustomRecipes(v1.9).jar:?]
	at CustomRecipes(v1.9).jar/me.mehboss.recipe.RecipeManager.addItems(RecipeManager.java:349) ~[CustomRecipes(v1.9).jar:?]
	at CustomRecipes(v1.9).jar/me.mehboss.recipe.Main.onEnable(Main.java:357) ~[CustomRecipes(v1.9).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-27-76c2f16]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-27-76c2f16]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-27-76c2f16]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-27-76c2f16]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at CustomRecipes(v1.9).jar/me.mehboss.recipe.NBTEditor.<clinit>(NBTEditor.java:60) ~[CustomRecipes(v1.9).jar:?]
	... 15 more


[08:26:15] [Server thread/ERROR]: Command exception: /crecipe
org.bukkit.command.CommandException: Cannot execute command 'crecipe' in plugin CustomRecipes v1.9 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-27-76c2f16]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:446) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.commands.Commands.performCommand(Commands.java:353) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.commands.Commands.performCommand(Commands.java:335) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1415) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.jar:1.21-27-76c2f16]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-27-76c2f16]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Server Version

1.21, Paper

### Plugin Version

1.9

### Server Mode

Offline Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello Nikoroq,
I apologize for this issue that was caused with the latest update and I will implement the fix and post the resource update shortly.
Thank you

**Comment by mehboss** [comment]
All set! Thanks for reporting
https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=553423
