### ISSUE TITLE
1.21 Issue - Plugin not loading on server start

### ISSUE THREAD

**Issue by Piqori** [mehboss/CustomRecipes#54]
### What happened?

Hello! Saw the new update for the plugin today so I wanted to try it again on my 1.21 server but it's still giving me an issue :(
just wanted to share because the plugin looks super interesting and I'm excited to try it!

![image_2024-07-18_180004712](https://github.com/user-attachments/assets/30b257ea-2eb2-4efb-a494-1f907f2a30c9)

### What was supposed to happen?

The plugin was meant to load.

### How do I reproduce this issue?

```bash
1. Install plugin to 1.21 Paper server
2. Start the server
3. rip
```

### Relevant log output

```shell
[16:53:43 ERROR]: Error occurred while enabling CustomRecipes v1.9.1 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at CustomRecipes.jar/me.mehboss.recipe.Main.getServerVersionParts(Main.java:544) ~[CustomRecipes.jar:?]
at CustomRecipes.jar/me.mehboss.recipe.Main.serverVersionAtLeast(Main.java:588) ~[CustomRecipes.jar:?]
at CustomRecipes.jar/me.mehboss.recipe.Main.onEnable(Main.java:374) ~[CustomRecipes.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-39-aa8d38d]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-39-aa8d38d]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-39-aa8d38d]
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-39-aa8d38d]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-39-aa8d38d]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-39-aa8d38d]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-39-aa8d38d]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-39-aa8d38d]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-39-aa8d38d]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Server Version

Paper 1.21

### Plugin Version

v1.9.1

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello Piqori,
I believe I have resolved the issue, but am unable to test it due to sign-in issues with the minecraft launcher. I will get back to you soon.

https://downdetector.com/status/minecraft/

Thank you

**Comment by mehboss** [comment]
This issue has been resolved. See [here.](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=563976)
Thank you for reporting.
