### ISSUE TITLE
Error loading the plugin

### ISSUE THREAD

**Issue by ZizionarD** [mehboss/CustomRecipes#59]
### What happened?

`[15:14:26 ERROR]: Error occurred while enabling CustomRecipes v1.9.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.RecipeChoice.clone()" because "this.template" is null
        at org.bukkit.inventory.SmithingTransformRecipe.getTemplate(SmithingTransformRecipe.java:50) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftSmithingTransformRecipe.addToCraftingManager(CraftSmithingTransformRecipe.java:33) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.addRecipe(CraftServer.java:1580) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.addRecipe(CraftServer.java:1546) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at org.bukkit.Bukkit.addRecipe(Bukkit.java:1112) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.mehboss.recipe.Main.onEnable(Main.java:370) ~[CustomRecipes-1.9.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:672) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]`

### What was supposed to happen?

Downloading the plugin

### How do I reproduce this issue?

```bash
1. Download the core: pufferfish-1.20.4
2. Install the plugin
3. Start the server
```

### Server Version

1.20.4

### Plugin Version

1.9.3

### Server Mode

Offline Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by Valorless** [comment]
Bad news, no clue what is wrong.
Good news, its fixed :D

**Comment by mehboss** [comment]
https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-21-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=565023
