### ISSUE TITLE
Error on startup, added for haven bags

### ISSUE THREAD

**Issue by SethXB** [mehboss/CustomRecipes#60]
### What happened?

Hello I get this error when starting the server, causing the plugin to disable itself. something related to being set to 0

### What was supposed to happen?

A successful startup of the plugin

### How do I reproduce this issue?

```bash
1.Download
2.Restart server
3.I may need to list you my plugins just let me know
...
```

### Relevant log output

```shell
Error occurred while enabling CustomRecipes v1.9.5 (Is it up to date?)
java.lang.IllegalArgumentException: amount must be greater than 0
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.of(ItemStack.java:59) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at CustomRecipes-1.9.5.jar/me.mehboss.recipe.RecipeManager.handleItemDamage(RecipeManager.java:97) ~[CustomRecipes-1.9.5.jar:?]
        at CustomRecipes-1.9.5.jar/me.mehboss.recipe.RecipeManager.addItems(RecipeManager.java:402) ~[CustomRecipes-1.9.5.jar:?]
        at CustomRecipes-1.9.5.jar/me.mehboss.recipe.Main.onEnable(Main.java:253) ~[CustomRecipes-1.9.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:07:10 INFO]: [CustomRecipes] Disabling CustomRecipes v1.9.5
```

### Relevant file configuration

```shell
Default config, I just downloaded.
```

### Server Version

1.21.1

### Plugin Version

1.9.5

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by Valorless** [comment]
Would you be so kind as you show us your recipe file? ^^
Its possible it could be related to the recipe setup :)

**Comment by SethXB** [comment]
This is using a fresh a fresh installation of customrecipes I have not added recipes yet. Although I do see a preset for havebags.yml so maybe thats the issue? I see nothing set to 0 other than the custom model data though. But here you go
[logs.txt](https://github.com/user-attachments/files/17355107/logs.txt)

**Comment by mehboss** [comment]
Hello,
Did the other two templates generate as well, or just haven bags? (CursedPick.yml and CursedSword.yml)

**Comment by SethXB** [comment]
Here is my current recipes.yml, all 3 are pasted in this log.txt, I do not see an amount set to 0 anywhere but I did notice haven bags item itself didnt have an amount so I tried adding "Amount: 1" to the backpack itself, and customrecipes now loads successfully but after doing /cr list I only see the curse tools not the backpack. 
[logs.txt](https://github.com/user-attachments/files/17356051/logs.txt)

**Comment by mehboss** [comment]
Awesome — progress. You won’t see HavenBags enabled unless you have the HavenBags and ValorUtils plugin installed on your server.

**Comment by SethXB** [comment]
Sorry to nag, or if Iim missing something, but I do have haven bags/val utils installed, and with the configs I sent, it does not show the havenbag recipe

**Comment by mehboss** [comment]
No worries. Happy to help. 
Does it show in /crecipe book?

**Comment by SethXB** [comment]
I do not see backpack no

**Comment by mehboss** [comment]
Can you enable debug (/crecipe debug), and then copy your startup log to pastebin.com

**Comment by mehboss** [comment]
When you changed this from “HavenBag:” to “Backpack1”, you renamed the HavenBag.yml to Backpack1.yml right?
![IMG_7510](https://github.com/user-attachments/assets/25499fc0-367a-4942-bb45-02879d9986ee)

**Comment by SethXB** [comment]
Sorry I wasn't around, I tried the update you made last night, the plugin is still failing to load, I also made the name change to the ywl as "Backpack1" and it didnt work, actually created a new Havebags yml on its own. Here are the logs, https://pastebin.com/ZP1RLZxy

**Comment by mehboss** [comment]
Can I see each individual recipe yml pasted in pastebin.com, with the links posted here. Seems like a configuration issue.

**Comment by SethXB** [comment]
havenbags.yml i renamed:
https://pastebin.com/cM3Du0UM

**Comment by SethXB** [comment]
CursedPick.yml
https://pastebin.com/0efhiTn2

**Comment by SethXB** [comment]
CursedSword.yml
https://pastebin.com/WZrnbAqc

**Comment by mehboss** [comment]
Is the havenbags.yml file named havenbags.yml or backpack1.yml

**Comment by SethXB** [comment]
Backpack1.yml

**Comment by SethXB** [comment]
https://imgur.com/a/pEoawEz

**Comment by mehboss** [comment]
In Backpack1.yml, you misspelled "   Ingredients:"

**Comment by SethXB** [comment]
That.. sure is somethin

**Comment by SethXB** [comment]
its empty, server auto generated it on startup once i renamed the original to "Backpack1.yml"

**Comment by mehboss** [comment]
Okay perfect.

**Comment by SethXB** [comment]
im restarting :p thanks sorry about that lets hope it works

**Comment by SethXB** [comment]
whelp, heres some more logs for ya

**Comment by SethXB** [comment]
https://pastebin.com/LJAbV2Kt

**Comment by mehboss** [comment]
org.bukkit.configuration.**InvalidConfigurationException:** while scanning for the next token
found character '\t(TAB)' that cannot start any token**. (Do not use \t(TAB) for indentation)**
 in 'reader', line 18, column 1:

It is still a configuration issue, can I see your update yml again

**Comment by SethXB** [comment]
https://pastebin.com/aM09NwJr

**Comment by SethXB** [comment]
says its valid on the first site, the 2nd site doesnt rlly say if any thing is wrong so idk

**Comment by mehboss** [comment]
Can you send the other ymls as well, just to double check

**Comment by SethXB** [comment]
https://pastebin.com/zr70Zxp1
https://pastebin.com/ppAF2xwR
the HavenBag.yml is still empty

**Comment by mehboss** [comment]
HavenBag.yml will be empty, that is fine.
https://pastebin.com/tN0Qwtt6
Perform a restart of the server after this change, do not do cr reload

**Comment by SethXB** [comment]
Aghhh one capital letter I swear, this is why I don't code

**Comment by SethXB** [comment]
Thanks its working Ill add recipes now, you coulda just said to read my configs and figure it out lol so I appreciate it!

**Comment by mehboss** [comment]
Haha, no worries. Happens to the best of us.
Thanks for sticking with it :)
